allowBuilds:
  esbuild: true
  msw: true
  sharp: true
minimumReleaseAgeExclude:
  - cnfast@0.0.8
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - esbuild
  - msw
  - sharp
